### PR TITLE
Add word filter (to demo version)

### PR DESCRIPTION
**Pull request by BenTBCampbell**
This is a word filter class that has two functions:

- `bool Filter.IsClean(string message)`: returns true if `message` doesn't contain any bad words. 
- `string Filter.RemoveBadWords(string message)`: replaces all the bad words in `message` with `?`

@usa4cc will need to review it since it has logic code.

### CODE REVIEW

**Review by usa4cc — CHANGES_REQUESTED** [review]
Question: so is the blacklist array everything; are we not using that extensive list that you downloaded anymore?

**Comment by BenTBCampbell** [comment]
Well, in the end I realized it would be pretty complicated to figure out
how to make it the extensive list. I think the best way would be to make it
an embedded file, but I think the list was too strict anyways, and the
actual list of words I wanted to block was actually quite small.

Remember, one of the agile principles is to focus on simplicity and try to
maximize the amount of work you don't need to do. I think we don't need to
figure out how to make the blacklist a text-file that is loaded if our
actual blacklist is only ten or so words.

If you know how to make it an external file, fell free! It would just take
me an hour or even several to figure it out myself.

**Comment by usa4cc** [comment]
Okay.

**Review by usa4cc — COMMENTED** [review]
Do we need to check for bad words and then also remove them?
Couldn't we just have a remove bad words function?

Or at least we can include a check bad words function, but don't do something like if (!IsClean(message))
{
RemoveBadWords(message);
}

Because we can just say remove bad words and not have to do leet replacements twice.

**Review by usa4cc — APPROVED** [review]
I implemented the filter to the production version as well.

**Pull request merged**
